"""Banco de exames do caso pulmão-rim.

Regra de ferro: o banco entrega o valor encontrado e o valor de referência.
Nada de interpretação, comentário didático, selo de relevância ou agrupamento.
O grupo interpreta; o sistema só informa. Valor fora da referência sai em
vermelho, e isso é tudo.

Um analito por entrada. Nomes de painel (hemograma, gasometria, função renal)
existem apenas como sinônimos, e listam os componentes.
"""

from motor.exames import an

BANCO = [
    an("Sedimento urinário",
       "<b>Hemácias dismórficas 40%</b> · <b>cilindros hemáticos presentes</b> · cilindros granulosos · leucócitos 8/campo · sem bacteriúria",
       ref="sem hemácias dismórficas, sem cilindros", cat="Urina", alterado=True,
       sin=["eas", "urina", "tipo", "1", "sumario", "de", "urina", "urina", "rotina", "sedimento", "síndrome pulmão-rim"]),
    an("Proteinúria de 24 horas",
       "2,4 g/24 h",
       ref="abaixo de 0,15 g/24 h", cat="Urina", alterado=True,
       sin=["proteinuria", "proteinuria 24h"]),
    an("Relação proteína/creatinina urinária",
       "2,1 mg/mg",
       ref="abaixo de 0,2 mg/mg", cat="Urina", alterado=True,
       sin=["relacao proteina creatinina", "pcr urinaria", "upcr"]),
    an("Hematúria",
       "++++ · 4+ na fita",
       ref="ausente", cat="Urina", alterado=True,
       sin=["hematuria", "sangue na urina"]),
    an("Eosinofilúria",
       "Ausente",
       ref="ausente", cat="Urina", alterado=False,
       sin=["eosinofiluria", "eosinofilos na urina"]),
    an("Urocultura",
       "Negativa",
       ref="negativa", cat="Microbiologia", alterado=False,
       sin=["urocultura", "cultura de urina"]),
    an("Creatinina",
       "Admissão 3,8 mg/dL · há 2 meses 1,0 mg/dL · 5º dia 4,6 mg/dL",
       ref="até 1,3 mg/dL", cat="Bioquímica", alterado=True,
       sin=["creatinina", "função renal"]),
    an("Ureia",
       "128 mg/dL",
       ref="até 45 mg/dL", cat="Bioquímica", alterado=True,
       sin=["ureia", "função renal"]),
    an("Taxa de filtração glomerular estimada",
       "17 mL/min/1,73 m²",
       ref="acima de 90 mL/min/1,73 m²", cat="Bioquímica", alterado=True,
       sin=["tfg", "clearance", "egfr", "ckd-epi", "função renal"]),
    an("Potássio",
       "5,4 mEq/L",
       ref="3,5 a 5,0 mEq/L", cat="Bioquímica", alterado=True,
       sin=["potassio", "k", "eletrólitos"]),
    an("Sódio",
       "136 mEq/L",
       ref="135 a 145 mEq/L", cat="Bioquímica", alterado=False,
       sin=["sodio", "na", "eletrólitos"]),
    an("Cálcio",
       "8,6 mg/dL",
       ref="8,5 a 10,2 mg/dL", cat="Bioquímica", alterado=False,
       sin=["calcio", "eletrólitos"]),
    an("Fósforo",
       "5,2 mg/dL",
       ref="2,5 a 4,5 mg/dL", cat="Bioquímica", alterado=True,
       sin=["fosforo", "fosfato", "eletrólitos"]),
    an("Bicarbonato",
       "15 mEq/L",
       ref="22 a 26 mEq/L", cat="Gasometria", alterado=True,
       sin=["bicarbonato", "hco3", "gasometria"]),
    an("pH arterial",
       "7,29",
       ref="7,35 a 7,45", cat="Gasometria", alterado=True,
       sin=["ph", "gasometria", "gasometria"]),
    an("pO2",
       "56 mmHg em ar ambiente",
       ref="80 a 100 mmHg", cat="Gasometria", alterado=True,
       sin=["po2", "gasometria"]),
    an("pCO2",
       "32 mmHg",
       ref="35 a 45 mmHg", cat="Gasometria", alterado=True,
       sin=["pco2", "gasometria"]),
    an("Relação PaO2/FiO2",
       "267",
       ref="acima de 300", cat="Gasometria", alterado=True,
       sin=["pafi", "p/f", "gasometria"]),
    an("Lactato",
       "1,6 mmol/L",
       ref="até 2,0 mmol/L", cat="Gasometria", alterado=False,
       sin=["lactato", "gasometria"]),
    an("Saturação de O2",
       "88% em ar ambiente · 94% com cateter a 4 L/min",
       ref="acima de 94%", cat="Gasometria", alterado=True,
       sin=["saturacao", "spo2", "gasometria"]),
    an("Hemoglobina",
       "Admissão 7,8 g/dL · há 2 meses 13,9 g/dL · 5º dia 6,9 g/dL",
       ref="13,5 a 17,5 g/dL", cat="Hemograma", alterado=True,
       sin=["hb", "hemoglobina", "hemograma"]),
    an("Hematócrito",
       "23,6%",
       ref="41 a 53%", cat="Hemograma", alterado=True,
       sin=["ht", "hematocrito", "hemograma"]),
    an("VCM",
       "88 fL",
       ref="80 a 100 fL", cat="Hemograma", alterado=False,
       sin=["vcm", "hemograma"]),
    an("Reticulócitos",
       "2,1%",
       ref="0,5 a 2,0%", cat="Hemograma", alterado=True,
       sin=["reticulocitos", "hemograma"]),
    an("Leucócitos",
       "Admissão 14.200/mm³ · 5º dia 1.900/mm³",
       ref="4.000 a 11.000/mm³", cat="Hemograma", alterado=True,
       sin=["leucocitos", "leucograma", "hemograma"]),
    an("Neutrófilos",
       "Admissão 11.800/mm³ · 5º dia 620/mm³",
       ref="1.800 a 7.000/mm³", cat="Hemograma", alterado=True,
       sin=["neutrofilos", "hemograma"]),
    an("Eosinófilos",
       "320/mm³ (2,3%)",
       ref="50 a 500/mm³", cat="Hemograma", alterado=False,
       sin=["eosinofilos", "hemograma"]),
    an("Linfócitos",
       "1.400/mm³",
       ref="1.000 a 4.000/mm³", cat="Hemograma", alterado=False,
       sin=["linfocitos", "hemograma"]),
    an("Plaquetas",
       "Admissão 468.000/mm³ · 5º dia 172.000/mm³",
       ref="150.000 a 450.000/mm³", cat="Hemograma", alterado=True,
       sin=["plaquetas", "hemograma", "coagulograma"]),
    an("Esfregaço de sangue periférico",
       "Sem esquizócitos · sem blastos · anisocitose discreta",
       ref="—", cat="Hemograma", alterado=False,
       sin=["esfregaco", "hematoscopia", "lamina", "hemograma"]),
    an("Coombs direto",
       "Negativo",
       ref="negativo", cat="Imunologia", alterado=False,
       sin=["coombs"]),
    an("Proteína C reativa",
       "Admissão 186 mg/L · 5º dia 204 mg/L",
       ref="até 5 mg/L", cat="Inflamação", alterado=True,
       sin=["pcr", "proteina c reativa", "provas de atividade inflamatória"]),
    an("VHS",
       "98 mm/h",
       ref="até 20 mm/h", cat="Inflamação", alterado=True,
       sin=["vhs", "hemossedimentacao", "provas de atividade inflamatória"]),
    an("Procalcitonina",
       "0,4 ng/mL · 5º dia 3,1 ng/mL",
       ref="abaixo de 0,5 ng/mL", cat="Inflamação", alterado=True,
       sin=["procalcitonina", "pct", "provas de atividade inflamatória"]),
    an("Ferritina",
       "640 ng/mL",
       ref="30 a 400 ng/mL", cat="Inflamação", alterado=True,
       sin=["ferritina", "provas de atividade inflamatória"]),
    an("Albumina",
       "2,9 g/dL",
       ref="3,5 a 5,2 g/dL", cat="Bioquímica", alterado=True,
       sin=["albumina"]),
    an("TAP / INR",
       "INR 1,1",
       ref="até 1,2", cat="Coagulação", alterado=False,
       sin=["inr", "tap", "coagulograma"]),
    an("TTPa",
       "Normal",
       ref="relação até 1,25", cat="Coagulação", alterado=False,
       sin=["ttpa", "coagulograma"]),
    an("Fibrinogênio",
       "542 mg/dL",
       ref="200 a 400 mg/dL", cat="Coagulação", alterado=True,
       sin=["fibrinogenio", "coagulograma"]),
    an("D-dímero",
       "1.840 ng/mL",
       ref="até 500 ng/mL", cat="Coagulação", alterado=True,
       sin=["d dimero", "coagulograma"]),
    an("ANCA por imunofluorescência indireta",
       "<b>Padrão perinuclear (p-ANCA), título 1:640</b>",
       ref="não reagente", cat="Imunologia", alterado=True,
       sin=["anca", "imunofluorescencia anca", "ifi anca", "p-anca", "c-anca", "painel de vasculite", "síndrome pulmão-rim"]),
    an("Anti-mieloperoxidase",
       "<b>148 U/mL</b>",
       ref="até 20 U/mL", cat="Imunologia", alterado=True,
       sin=["anti-mpo", "mpo", "antimieloperoxidase", "painel de vasculite"]),
    an("Anti-proteinase 3",
       "Não reagente (3 U/mL)",
       ref="até 20 U/mL", cat="Imunologia", alterado=False,
       sin=["anti-pr3", "pr3", "antiproteinase", "painel de vasculite"]),
    an("Anticorpo anti-membrana basal glomerular",
       "<b>Não reagente</b>",
       ref="não reagente", cat="Imunologia", alterado=False,
       sin=["anti-mbg", "anti-gbm", "goodpasture", "mbg", "painel de vasculite", "síndrome pulmão-rim"]),
    an("Complemento C3",
       "112 mg/dL",
       ref="90 a 180 mg/dL", cat="Imunologia", alterado=False,
       sin=["c3", "complemento", "painel de vasculite"]),
    an("Complemento C4",
       "28 mg/dL",
       ref="10 a 40 mg/dL", cat="Imunologia", alterado=False,
       sin=["c4", "painel de vasculite"]),
    an("FAN",
       "Não reagente",
       ref="não reagente", cat="Imunologia", alterado=False,
       sin=["fan", "antinuclear", "painel de vasculite"]),
    an("Anti-DNA nativo",
       "Não reagente",
       ref="não reagente", cat="Imunologia", alterado=False,
       sin=["anti-dna", "dna nativo", "anti-dsdna", "painel de vasculite"]),
    an("Anti-ENA",
       "Não reagente para Sm, RNP, SSA e SSB",
       ref="não reagente", cat="Imunologia", alterado=False,
       sin=["ena", "anti-ena", "ssa", "ssb", "sm", "rnp"]),
    an("Crioglobulinas",
       "Negativas — coleta em tubo aquecido a 37 °C e transporte aquecido",
       ref="negativas", cat="Imunologia", alterado=False,
       sin=["crioglobulinas", "crioglobulina", "painel de vasculite"]),
    an("Fator reumatoide",
       "18 UI/mL",
       ref="até 20 UI/mL", cat="Imunologia", alterado=False,
       sin=["fator reumatoide", "fr"]),
    an("Anticorpos antifosfolípides",
       "Anticardiolipina, anti-beta-2-glicoproteína I e anticoagulante lúpico não reagentes",
       ref="não reagentes", cat="Imunologia", alterado=False,
       sin=["antifosfolipide", "anticardiolipina", "anticoagulante lupico", "beta 2", "painel de vasculite"]),
    an("Eletroforese de proteínas",
       "Sem pico monoclonal · hipoalbuminemia · gama policlonal discretamente elevada",
       ref="sem pico monoclonal", cat="Imunologia", alterado=False,
       sin=["eletroforese", "proteinograma"]),
    an("Imunoglobulinas séricas",
       "IgG 1.180 · IgA 240 · IgM 96 mg/dL",
       ref="IgG 700 a 1.600 mg/dL", cat="Imunologia", alterado=False,
       sin=["imunoglobulinas", "igg", "iga", "igm"]),
    an("Hemocultura",
       "Admissão: 3 pares negativos em 5 dias · 5º dia: <b>Staphylococcus aureus</b> em 2 de 2 pares, sensível a oxacilina",
       ref="negativa", cat="Microbiologia", alterado=True,
       sin=["hemocultura", "cultura de sangue"]),
    an("Cultura do lavado broncoalveolar",
       "Admissão negativa para bactérias, fungos e micobactérias",
       ref="negativa", cat="Microbiologia", alterado=False,
       sin=["cultura do lba", "cultura lavado"]),
    an("Pesquisa de Pneumocystis no lavado",
       "Não detectado",
       ref="não detectado", cat="Microbiologia", alterado=False,
       sin=["pneumocystis", "pcp", "jirovecii"]),
    an("Baciloscopia e teste molecular para tuberculose",
       "Baciloscopia negativa · MTB não detectado · cultura negativa em 8 semanas",
       ref="negativos", cat="Microbiologia", alterado=False,
       sin=["bk", "baciloscopia", "trm", "genexpert", "tb"]),
    an("Galactomanana e beta-D-glucana",
       "Não reagentes",
       ref="não reagentes", cat="Microbiologia", alterado=False,
       sin=["galactomanana", "beta d glucana", "aspergillus"]),
    an("Anti-HIV",
       "Não reagente",
       ref="não reagente", cat="Sorologia", alterado=False,
       sin=["hiv", "anti hiv", "sorologias virais"]),
    an("HBsAg e anti-HBc",
       "Não reagentes",
       ref="não reagentes", cat="Sorologia", alterado=False,
       sin=["hbsag", "hepatite b", "anti hbc", "sorologias virais"]),
    an("Anti-HCV",
       "Não reagente",
       ref="não reagente", cat="Sorologia", alterado=False,
       sin=["anti hcv", "hepatite c", "sorologias virais"]),
    an("Sorologia para sífilis",
       "Não reagente",
       ref="não reagente", cat="Sorologia", alterado=False,
       sin=["vdrl", "sifilis"]),
    an("Tomografia de tórax",
       "<b>Opacidades em vidro fosco difusas e bilaterais</b>, confluentes em alguns lobos · sem nódulo escavado · sem massa · sem linfonodomegalia · sem derrame pleural",
       ref="—", cat="Imagem", alterado=True,
       sin=["tc torax", "tomografia de torax", "síndrome pulmão-rim"]),
    an("Radiografia de tórax",
       "Opacidades alveolares bilaterais e simétricas · área cardíaca normal · sem derrame",
       ref="—", cat="Imagem", alterado=True,
       sin=["rx torax", "raio x de torax"]),
    an("Tomografia de seios da face",
       "Espessamento mucoso discreto em seios maxilares · <b>sem erosão óssea, sem massa, sem destruição septal</b>",
       ref="—", cat="Imagem", alterado=False,
       sin=["tc seios da face", "seios paranasais", "sinusite"]),
    an("Ultrassonografia de rins e vias urinárias",
       "Rins de dimensões normais (11,2 e 11,0 cm) · <b>relação córtico-medular preservada</b> · sem hidronefrose · sem cálculo",
       ref="—", cat="Imagem", alterado=False,
       sin=["usg rins", "ultrassom renal", "ecografia renal"]),
    an("Ecocardiograma transtorácico",
       "Sem vegetações · fração de ejeção 61% · sem derrame pericárdico · pressão sistólica de artéria pulmonar 34 mmHg",
       ref="—", cat="Imagem", alterado=False,
       sin=["eco", "ecocardiograma"]),
    an("Angiotomografia de tórax",
       "Sem falha de enchimento nas artérias pulmonares",
       ref="—", cat="Imagem", alterado=False,
       sin=["angiotc", "angiotomografia", "tep", "embolia pulmonar"]),
    an("Angiografia renal",
       "Não realizada",
       ref="—", cat="Imagem", alterado=False,
       sin=["angiografia renal", "arteriografia"]),
    an("PET-CT",
       "Não realizado",
       ref="—", cat="Imagem", alterado=False,
       sin=["pet", "pet ct"]),
    an("Biópsia renal — microscopia óptica",
       "24 glomérulos · <b>crescentes celulares em 15 deles (62%)</b> · necrose fibrinoide segmentar · sem esclerose global significativa · fibrose intersticial em 10% do córtex",
       ref="—", cat="Anatomia patológica", alterado=True,
       sin=["biopsia renal", "biopsia do rim", "microscopia optica", "biópsia renal"]),
    an("Biópsia renal — imunofluorescência",
       "<b>Ausência de depósitos significativos de IgG, IgA, IgM, C3 e C1q</b> — padrão pauci-imune · <b>sem depósito linear</b> ao longo da membrana basal",
       ref="—", cat="Anatomia patológica", alterado=True,
       sin=["imunofluorescencia renal", "if renal", "pauci-imune", "síndrome pulmão-rim", "biópsia renal"]),
    an("Biópsia renal — classificação de Berden",
       "<b>Classe crescêntica</b> (mais de 50% dos glomérulos com crescentes celulares)",
       ref="—", cat="Anatomia patológica", alterado=True,
       sin=["berden", "classificacao histologica", "biópsia renal"]),
    an("Lavado broncoalveolar",
       "<b>Alíquotas sequencialmente mais hemorrágicas</b> · <b>hemossiderófagos em 34% dos macrófagos</b> · culturas negativas",
       ref="hemossiderófagos abaixo de 20%", cat="Procedimento", alterado=True,
       sin=["lba", "lavado broncoalveolar", "broncoscopia", "síndrome pulmão-rim"]),
    an("Biópsia de pele da lesão purpúrica",
       "Não realizada",
       ref="—", cat="Anatomia patológica", alterado=False,
       sin=["biopsia de pele", "biopsia cutanea", "purpura"]),
    an("Biópsia de nervo sural",
       "Não realizada",
       ref="—", cat="Procedimento", alterado=False,
       sin=["biopsia de nervo", "sural"]),
    an("Biópsia pulmonar",
       "Não realizada",
       ref="—", cat="Procedimento", alterado=False,
       sin=["biopsia pulmonar", "biopsia de pulmao"]),
    an("Eletroneuromiografia",
       "<b>Mononeuropatia múltipla</b> de padrão axonal · comprometimento assimétrico do fibular comum direito e do ulnar esquerdo · potenciais sensitivos reduzidos nos mesmos territórios",
       ref="—", cat="Neurofisiologia", alterado=True,
       sin=["enmg", "eletroneuromiografia", "emg", "conducao nervosa"]),
    an("Espirometria com DLCO",
       "Não realizada — paciente hipoxêmico e dispneico",
       ref="—", cat="Neurofisiologia", alterado=False,
       sin=["espirometria", "dlco", "difusao"]),
    an("Eletrocardiograma",
       "Ritmo sinusal, FC 104 bpm · sem alteração isquêmica · sem sinal de hipercalemia",
       ref="—", cat="Imagem", alterado=False,
       sin=["ecg", "eletrocardiograma"]),
]
