"""Caso autoral de diarreia e citopenias após transplante renal."""
from pathlib import Path
from motor.etapas import capa,pagina,p,vitais,topicos,lamina
from casos.novos import pg,q,labs,bif,fim
TITULO='Depois da travessia'
RODAPE='Paciente ficcional · evoluções simuladas para ensino'
IMG=Path(__file__).parents[1]/'pulmao_rim'/'img'
BANCO=[]
ETAPAS=[
 capa(TITULO,fundo='',kicker='Caso interativo',procedencia='Paciente ficcional. Curso autoral e simulado.'),
 pg('historia','Apresentação','Helena, 58 anos, retorna ao hospital por seis dias de diarreia e cansaço. Fez transplante renal há quatro meses e vinha retomando as atividades da casa. Nos últimos dois dias apresentou febre de até 38,4 °C e deixou de conseguir completar as refeições.','Tem seis a oito evacuações aquosas por dia, inclusive durante a noite, acompanhadas de cólicas. Não observou sangue. A família acredita que algum medicamento esteja irritando o intestino.'),
 pg('hda','História da doença atual','No começo, a diarreia ocorria apenas após as refeições. Agora persiste mesmo com baixa ingestão. Não há vômitos, dor localizada no enxerto, ardor para urinar, tosse ou falta de ar. Perdeu 2 kg nesta semana e percebeu redução da diurese.','Ninguém em casa está doente. Nega viagens recentes, água não tratada ou alimento suspeito. Recebeu amoxicilina-clavulanato para sinusite cinco semanas antes.'),
 pg('antecedentes','Transplante e medicações','Doença renal terminal atribuída a diabetes e hipertensão, com três anos de hemodiálise antes do transplante de doador falecido. Creatinina basal após o procedimento: 1,2 mg/dL. Não houve episódio documentado de rejeição.','Usa tacrolimo, micofenolato mofetil e prednisona, além de insulina, anlodipino e profilaxia para pneumocistose. A profilaxia antiviral foi encerrada conforme o protocolo da equipe após três meses. A paciente era soropositiva para CMV antes do transplante. Não mudou as doses por conta própria.'),
 pagina('exame','Exame físico','',vitais(('PA','100/62 mmHg',False),('FC','108 bpm',True),('FR','18 irpm',False),('Temperatura','38,2 °C',True),('SpO₂','97% em ar ambiente',False)),topicos(('Estado geral','Alerta, mucosas secas, enchimento capilar preservado.'),('Cardiopulmonar','Taquicardia regular, sem sopro; ausculta pulmonar normal.'),('Abdome','Dolorimento difuso leve, sem defesa. Enxerto na fossa ilíaca direita indolor.'),('Pele e neurologia','Sem exantema ou déficit focal. Não há edema.')),so_kicker=True),
 q('p1',1,'Qual estratégia inicial melhor combina o risco infeccioso com as causas medicamentosas da diarreia?',[
 ('Suspender todos os imunossupressores e aguardar resolução',False,'Expõe o enxerto à rejeição; mudanças devem ser individualizadas com a equipe de transplante.'),
 ('Hidratar, colher exames e investigar infecção, revisando níveis e toxicidade das medicações',True,'As duas possibilidades podem coexistir e a desidratação altera a função renal e a exposição a fármacos.'),
 ('Atribuir o quadro ao micofenolato pela frequência desse efeito adverso',False,'Febre e repercussão sistêmica exigem avaliar infecção antes de encerrar o raciocínio.'),
 ('Tratar rejeição com pulso de corticoide a partir da redução da diurese',False,'Oligúria neste contexto pode decorrer de hipovolemia ou toxicidade e não confirma rejeição.')]),
 labs('res1','Admissão',[
 ('Hemoglobina','10,1 g/dL','12–16 g/dL',True),('Leucócitos','2.100/mm³','4.000–11.000/mm³',True),('Neutrófilos','1.200/mm³','1.500–7.500/mm³',True),('Plaquetas','112.000/mm³','150.000–400.000/mm³',True),('Creatinina','2,1 mg/dL (basal 1,2)','0,6–1,1 mg/dL',True),('Potássio','4,6 mmol/L','3,5–5,0 mmol/L',False),('AST / ALT','62 / 71 U/L','até 35 / 35 U/L',True),('Tacrolimo — vale','14 ng/mL','Alvo individual: 5–8 ng/mL',True)],'A equipe solicita hemoculturas, pesquisa de patógenos nas fezes e quantificação de CMV no plasma.'),
 pg('evolucao1','Após hidratação','A pressão melhora e a creatinina cai para 1,6 mg/dL. A ultrassonografia do enxerto, realizada pela equipe, não mostra obstrução ou alteração vascular relevante. A dose do tacrolimo é revista conforme seu nível e a função renal.','A febre e a diarreia persistem. Hemoculturas permanecem negativas. A investigação para Clostridioides difficile e o painel de patógenos entéricos comuns são negativos.'),
 pagina('rx','Avaliação torácica','',p('A radiografia, obtida durante a investigação da febre, não mostra infiltrado. A saturação permanece normal. A avaliação se concentra na síndrome gastrointestinal com citopenias.'),lamina_=lamina('rx_torax_normal.jpg','Radiografia de tórax','Figura comparativa de outro paciente; não é registro de Helena.','Mikael Häggström · Wikimedia Commons · CC0'),so_kicker=True),
 q('p2',2,'A creatinina melhorou, mas a diarreia, a febre e as citopenias persistem. Quais duas interpretações são adequadas?',[
 ('O nível alto de tacrolimo explica necessariamente todo o quadro',False,'Pode contribuir para a lesão renal, mas não deve encerrar a investigação da síndrome febril.'),
 ('Resultado negativo nas fezes exclui infecção gastrointestinal oportunista',False,'Os painéis não pesquisam todos os agentes nem substituem avaliação de doença tecidual.'),
 ('A cronologia da imunossupressão e da profilaxia modifica a probabilidade de infecção oportunista',True,'A história do transplante orienta hipóteses, sem funcionar como diagnóstico isolado.'),
 ('Endoscopia com biópsias pode distinguir lesão medicamentosa de doença infecciosa tecidual',True,'É útil na persistência do quadro após a investigação inicial.')]),
 pg('virologia','Resultado virológico','A quantificação plasmática de CMV é de 18.600 UI/mL. O exame demonstra replicação viral, mas não localiza sozinho a doença. Helena continua com sete evacuações diárias e baixa ingestão.','A equipe discute endoscopia com biópsias das áreas alteradas. A questão é se há lesão intestinal atribuível ao vírus, a medicamento ou a outro processo.'),
 q('p3',3,'O que o resultado plasmático permite afirmar?',[
 ('Há evidência de replicação; a relação com a lesão intestinal precisa de correlação e, quando viável, tecido',True,'DNAemia e doença invasiva não são sinônimos. A biópsia pode demonstrar envolvimento tecidual.'),
 ('O valor estabelece sozinho colite invasiva e sua extensão',False,'O sangue não mostra diretamente a localização nem a extensão da lesão.'),
 ('A presença de DNA viral exclui toxicidade pelo micofenolato',False,'Mecanismos podem coexistir no transplantado.'),
 ('Uma segunda quantificação negativa excluiria qualquer doença gastrointestinal pelo vírus',False,'Doença localizada pode ocorrer sem DNAemia detectável, dependendo do contexto.')]),
 bif('b1','A paciente mantém febre, diarreia importante e dificuldade para tomar medicamentos. Qual conduta você adota?',[
 ('Tratar a suspeita de doença por CMV e obter biópsias, coordenando ajustes com o transplante','endoscopia','A gravidade e a absorção duvidosa favorecem terapia intravenosa inicial; tecido esclarece a doença intestinal.'),
 ('Reduzir apenas o micofenolato e observar, atribuindo a diarreia à medicação','atraso','A toxicidade é plausível, mas não explica com segurança a combinação de febre, citopenias e DNAemia.'),
 ('Intensificar corticoide por suspeita de rejeição do enxerto','imunossupressao','Sem demonstrar rejeição, aumentar imunossupressão pode agravar uma infecção ativa.')]),
 pg('atraso','Quatro dias depois','A diarreia não diminui. Helena passa a apresentar sangue nas fezes e a creatinina sobe para 2,3 mg/dL. O hemograma mantém citopenias.','A equipe revê a hipótese, indica tratamento antiviral e endoscopia. O atraso trouxe desidratação e maior comprometimento nutricional neste percurso.',segue='endoscopia'),
 pg('imunossupressao','Após a intensificação','A febre aumenta e a paciente desenvolve dor abdominal mais intensa, com sinais de irritação peritoneal. Tomografia urgente demonstra perfuração intestinal. A equipe inicia abordagem cirúrgica, suporte e tratamento anti-infeccioso.',segue='f3'),
 pg('endoscopia','Endoscopia e biópsias','A colonoscopia mostra úlceras em segmentos do cólon. As amostras revelam inflamação, células aumentadas com inclusões virais e imunohistoquímica positiva para CMV. O conjunto confirma doença gastrointestinal invasiva por CMV.','A aparência endoscópica isolada não seria suficiente para identificar o agente. O diagnóstico se apoia na relação entre clínica e demonstração do vírus no tecido.'),
 pg('tratamento','Tratamento inicial','É iniciado ganciclovir intravenoso, com dose calculada pela função renal e revista à medida que a hidratação melhora a depuração. A equipe acompanha hemograma, creatinina, tolerância e quantificação viral seriada.','A revisão da imunossupressão é coordenada com o transplante. Não se suspendem todos os fármacos indiscriminadamente. A transição para valganciclovir oral depende de melhora clínica e absorção confiável.'),
 q('p4',4,'Após uma semana, a diarreia melhora e a carga viral diminui. Os neutrófilos caem para 700/mm³. Qual resposta é mais apropriada?',[
 ('Reduzir automaticamente o antiviral abaixo da dose ajustada à função renal',False,'Subdose pode comprometer eficácia; leucopenia exige revisão dos demais fármacos e medidas de suporte.'),
 ('Suspender definitivamente o tratamento porque a diarreia melhorou',False,'A melhora clínica é importante, mas o término também depende da resposta virológica e da duração adequada.'),
 ('Rever medicamentos mielotóxicos, função renal e suporte hematológico com a equipe',True,'Busca controlar a citopenia sem deixar a infecção inadequadamente tratada.'),
 ('Concluir resistência viral pela neutropenia',False,'Neutropenia não é critério de resistência e pode refletir doença ou medicamentos.')]),
 pg('evolucao2','Segunda semana','Após ajustes coordenados e suporte, neutrófilos sobem para 1.400/mm³. Helena está afebril, volta a se alimentar e evacua duas vezes ao dia. Creatinina é 1,3 mg/dL. O tratamento passa à via oral com dose ajustada.','A carga viral ainda é detectável, embora em queda. Não é correto encerrar o tratamento apenas por ter alcançado uma data fixa ou desaparecido a diarreia.'),
 bif('b2','Como definir o término do tratamento?',[
 ('Integrar resolução clínica e resposta virológica, respeitando o mínimo terapêutico e o método do laboratório','resposta','O consenso recomenda pelo menos duas semanas e continuidade até resposta clínica e supressão virológica adequada.'),
 ('Parar imediatamente porque já não há febre nem diarreia relevante','recaida','Sintomas podem melhorar antes do controle virológico suficiente; a decisão isolada aumenta risco de recaída.')]),
 pg('resposta','Seguimento','Com acompanhamento semanal, a quantificação cai abaixo do limiar utilizado pela equipe e a paciente permanece sem sintomas. O tratamento é encerrado após avaliação clínica e virológica.','É combinado um plano de vigilância após o término. Profilaxia secundária não é automática: a equipe considera risco individual, intensidade da imunossupressão e capacidade de monitorização.',segue='f1'),
 fim('f1','Retorno ao ambulatório','Helena mantém boa função do enxerto, alimentação adequada e recuperação do hemograma. Segue em acompanhamento próximo após o episódio.','Tratamento eficaz precisou conciliar absorção, função renal, toxicidade hematológica e resposta virológica.','melhor'),
 pg('recaida','Duas semanas depois','A paciente volta com diarreia e febre. A carga viral aumentou. A equipe revê adesão, dose, absorção e imunossupressão antes de atribuir o problema a resistência antiviral.',segue='f2'),
 fim('f2','Reinternação','O tratamento é retomado e a investigação reavaliada. A paciente recupera o controle da infecção após nova internação neste cenário.','Encerrar precocemente produziu uma recaída simulada; não prova resistência nem obriga troca automática de antiviral.','medio'),
 fim('f3','Complicação grave','Apesar da cirurgia e do suporte intensivo, Helena apresenta sepse abdominal, perda da função do enxerto e necessidade de diálise. Permanece hospitalizada ao final deste percurso.','A evolução é hipotética: intensificar imunossupressão durante infecção não controlada pode agravar a doença. Perfuração é uma complicação possível, não inevitável.','pior'),
 pg('retrospectiva','Retrospectiva','Havia mais de um mecanismo: desidratação e nível alto de tacrolimo contribuíram para a creatinina, enquanto a doença intestinal explicava a persistência da síndrome. Corrigir um problema não resolveu o outro.','DNAemia direcionou a investigação; tecido confirmou invasão. A decisão de terminar tratamento exigiu observar a paciente e a evolução virológica.'),
 pg('referencias','Fontes e limites','Caso e trajetórias ficcionais; não reproduzem um paciente publicado.','Kotton et al. The Fourth International Consensus Guidelines on the Management of Cytomegalovirus in Solid Organ Transplantation. Transplantation, 2025. <a href="https://doi.org/10.1097/TP.0000000000005374" target="_blank" rel="noopener">Abrir referência</a>','Radiografia comparativa: Mikael Häggström, Wikimedia Commons, CC0. Endoscopia e histologia são descritas como resultados simulados; não há figura atribuída ao paciente.')
]
