"""Caso autoral: hipercalcemia, doença granulomatosa e comprometimento ocular."""
from pathlib import Path
from motor.etapas import capa,pagina,p,vitais,topicos
from casos.novos import pg,q,labs,bif,fim
TITULO='Entre a sede e o fôlego'
RODAPE='Paciente ficcional · evoluções simuladas para ensino'
IMG=Path(__file__).parents[1]/'pulmao_rim'/'img'
BANCO=[]
ETAPAS=[
 capa(TITULO,fundo='',kicker='Caso interativo',procedencia='Paciente ficcional. Curso autoral e simulado.'),
 pg('historia','Apresentação','Rafael, 41 anos, procura a emergência por náuseas, constipação e dificuldade para se concentrar. Há uma semana bebe água repetidamente e acorda três vezes à noite para urinar. A esposa percebeu que ele ficou mais lento para responder.','Antes disso, vinha reduzindo as caminhadas por cansaço. Atribuiu o problema ao trabalho e a uma tosse seca intermitente que começou dois meses antes.'),
 pg('hda','História da doença atual','A tosse não produz secreção nem sangue. Há desconforto ao subir dois lances de escada, sem ortopneia ou dor torácica. Não mediu febre. Perdeu aproximadamente 4 kg em oito semanas, com redução recente do apetite.','A sede precedeu as náuseas. Nega vômitos persistentes, diarreia, cólica renal ou redução da diurese. Não houve síncope, palpitação sustentada ou perda de força focal. Não tinha alterações visuais na primeira consulta.'),
 pg('antecedentes','Antecedentes e exposições','Hipertenso há cinco anos, usa hidroclorotiazida 25 mg/dia. Começou por conta própria colecalciferol 5.000 UI/dia há três meses, após ouvir que melhoraria a disposição. Não usa cálcio, lítio ou antiácidos regularmente. Sem doença renal ou cálculos prévios.','Trabalha em escritório administrativo; nega atividades com corte de pedra, metal, cerâmica ou exposição conhecida a berílio. Não fuma. Não há história familiar de hipercalcemia. Mora em área urbana e não recorda contato com tuberculose.'),
 pagina('exame','Exame físico','',vitais(('PA','104/66 mmHg',False),('FC','102 bpm',True),('FR','20 irpm',False),('Temperatura','36,8 °C',False),('SpO₂','95% em ar ambiente',False)),topicos(('Estado geral e neurologia','Desidratado, orientado, com atenção reduzida; sem déficit focal.'),('Cardiovascular','Ritmo regular, sem sopro ou turgência jugular.'),('Pulmonar','Murmúrio vesicular presente; raros estertores finos bilaterais.'),('Abdome','Ruídos diminuídos, sem dor à palpação ou massa.'),('Pele e membros','Sem edema, sinovite ou lesão cutânea específica.')),so_kicker=True),
 labs('res1','Exames na emergência',[
 ('Cálcio total','13,6 mg/dL','8,5–10,5 mg/dL',True),('Albumina','4,0 g/dL','3,5–5,0 g/dL',False),('Cálcio ionizado','1,72 mmol/L','1,12–1,32 mmol/L',True),('Creatinina','2,0 mg/dL (prévia 1,0)','0,7–1,3 mg/dL',True),('Ureia','72 mg/dL','15–45 mg/dL',True),('Sódio / potássio','143 / 3,5 mmol/L','135–145 / 3,5–5,0',False),('Hemoglobina','12,8 g/dL','13,5–17,5 g/dL',True),('Glicemia','102 mg/dL','70–99 mg/dL em jejum',False)],'Exames obtidos durante a avaliação de sede, poliúria e lentificação.'),
 q('p1',1,'A hipercalcemia é confirmada e acompanha desidratação e lesão renal. Quais duas medidas têm prioridade?',[
 ('Reposição de volume com solução isotônica, ajustada à avaliação cardiopulmonar',True,'A depleção de volume reduz a excreção de cálcio; hidratação exige reavaliações clínicas.'),
 ('Furosemida antes de repor volume, para aumentar a calciúria',False,'Pode agravar a depleção de volume; não é tratamento rotineiro da hipercalcemia sem sobrecarga.'),
 ('Suspender tiazídico e vitamina D e dosar PTH',True,'Retira possíveis contribuintes e separa mecanismos dependentes e independentes de PTH.'),
 ('Aguardar a investigação etiológica completa antes de tratar',False,'Sintomas neurológicos e lesão renal justificam tratamento enquanto a investigação ocorre.')]),
 pg('evolucao1','Primeiras 24 horas','Após hidratação monitorada e suspensão das duas medicações, Rafael fica mais atento. O cálcio cai para 12,4 mg/dL e a creatinina para 1,6 mg/dL. O PTH é 6 pg/mL, abaixo da referência de 15–65 pg/mL.','A melhora parcial não esclarece a causa. A tosse e a perda de peso continuam sem explicação.'),
 q('p2',2,'Com PTH suprimido, quais dois conjuntos de exames ajudam mais a definir a investigação seguinte?',[
 ('25-hidroxivitamina D e 1,25-di-hidroxivitamina D',True,'Permitem distinguir excesso de substrato de produção aumentada de calcitriol.'),
 ('Ultrassonografia das paratireoides e cintilografia com sestamibi',False,'Localizam lesões quando há doença dependente de PTH; não explicam um PTH suprimido.'),
 ('Radiografia de tórax e avaliação dirigida para neoplasia ou doença granulomatosa',True,'Integra os sintomas respiratórios e constitucionais à hipercalcemia.'),
 ('Dosagem de calcitonina como teste confirmatório da causa',False,'Não é o teste central para discriminar essas hipóteses.')]),
 labs('res2','Investigação do metabolismo do cálcio',[
 ('25-OH-vitamina D','38 ng/mL','20–50 ng/mL',False),('1,25-(OH)₂-vitamina D','104 pg/mL','18–72 pg/mL',True),('PTHrP','Não elevada','Conforme método',False),('Eletroforese sérica','Sem componente monoclonal','Ausente',False),('Fósforo','3,6 mg/dL','2,5–4,5 mg/dL',False)],'A radiografia mostra aumento hilar bilateral. A equipe solicita tomografia para caracterizar a distribuição.'),
 pg('tomografia','Tomografia de tórax','O laudo descreve linfonodos hilares e mediastinais bilaterais, relativamente simétricos, e pequenos nódulos em distribuição perilinfática, incluindo regiões peribroncovasculares e fissuras. Não há cavitação ou derrame pleural.','Este é um laudo simulado. O padrão não distingue sozinho sarcoidose, infecção granulomatosa e algumas neoplasias.'),
 q('p3',3,'A tomografia e o calcitriol elevado modificam o diferencial. Qual afirmação melhor orienta o próximo passo?',[
 ('A simetria dos linfonodos dispensa exclusão de infecção',False,'A distribuição é sugestiva, mas não específica o suficiente para dispensar alternativas relevantes.'),
 ('Granulomas não necrosantes, se encontrados, definem a etiologia sem outros testes',False,'Granuloma é um padrão de resposta tecidual; pode ter mais de uma causa.'),
 ('É necessário integrar exposição, microbiologia e tecido, se indicado, antes de atribuir uma etiologia',True,'O diagnóstico depende da combinação de apresentação compatível, evidência tecidual e exclusão razoável de alternativas.'),
 ('O nível de enzima conversora de angiotensina substitui a biópsia',False,'Tem limitações de sensibilidade e especificidade e não resolve isoladamente o caso.')]),
 bif('b1','Rafael está estável após hidratação, sem ameaça respiratória imediata. Como conduzir a definição etiológica?',[
 ('Obter amostra ganglionar por EBUS, com histologia e estudos microbiológicos','tecido','Permite abordar linfonodos intratorácicos e pesquisar mecanismos alternativos antes de imunossuprimir.'),
 ('Iniciar corticoide sem amostragem e considerar a resposta como confirmação','empirico','A resposta pode ocorrer em doenças diferentes e não estabelece a causa.'),
 ('Atribuir tudo ao suplemento e acompanhar sem investigar o tórax','suplemento','O suplemento pode contribuir, mas não explica por si a adenopatia e o padrão de calcitriol.')]),
 pg('empirico','Após dez dias','O cálcio diminui e Rafael respira melhor. Entretanto, o tratamento foi iniciado sem amostra e ainda não existe exclusão adequada de infecção ou linfoma. A consulta especializada identifica essa lacuna.','A equipe reorganiza a investigação; melhorar sob corticoide não encerra o problema.',segue='tecido'),
 pg('suplemento','Uma semana depois','Mesmo sem suplemento ou tiazídico, o cálcio volta a 13,1 mg/dL. A tosse persiste e Rafael relata dor ocular com sensibilidade à luz. A equipe indica nova avaliação hospitalar e oftalmológica.',segue='tecido'),
 pg('tecido','Amostragem e avaliação adicional','A punção de linfonodos por EBUS mostra granulomas não necrosantes. As colorações para fungos e bacilos são negativas; teste molecular para tuberculose e culturas das amostras não demonstram agente. A investigação não mostra neoplasia.','A revisão das exposições não identifica causa ocupacional. A avaliação oftalmológica confirma uveíte anterior. O conjunto sustenta sarcoidose sistêmica com alteração do metabolismo do cálcio e acometimento ocular.'),
 pg('extensao','Avaliação de outros órgãos','A equipe registra ECG, função renal e hepática, hemograma, espirometria e capacidade de difusão. O ECG não mostra alteração de condução. Não há síncope nem palpitação. A capacidade de difusão está reduzida, em 64% do previsto.','Creatinina permanece em 1,5 mg/dL. A uveíte requer tratamento específico e acompanhamento. Não é suficiente classificar a doença apenas pelo aspecto da radiografia.'),
 q('p4',4,'Qual combinação melhor justifica tratar este paciente, em vez de somente observar?',[
 ('A presença isolada de linfonodos hilares, independentemente de sintomas',False,'Alguns pacientes com adenopatia isolada podem ser observados; a decisão considera repercussão.'),
 ('Hipercalcemia recorrente, repercussão renal e inflamação ocular',True,'Há manifestações com potencial de dano orgânico, além de alteração radiológica.'),
 ('Qualquer granuloma em qualquer órgão',False,'O padrão histológico não determina sozinho necessidade e intensidade do tratamento.'),
 ('O desejo de normalizar imediatamente todas as imagens',False,'A meta é controlar atividade e preservar função, não perseguir uma radiografia normal a qualquer custo.')]),
 pg('tratamento','Tratamento','Após a investigação das alternativas, a equipe inicia glicocorticoide sistêmico com plano de redução individualizado e tratamento ocular orientado pelo oftalmologista. Mantém monitorização de cálcio e função renal e evita reposição automática de vitamina D e cálcio.','A dose e a duração são revistas conforme órgão acometido, resposta e efeitos adversos. Antes de tratamento prolongado, são avaliados risco infeccioso, glicemia, pressão arterial e proteção óssea compatível com a hipercalcemia.'),
 pg('evolucao2','Seis semanas depois','A sede desapareceu. Cálcio é 9,8 mg/dL e creatinina 1,1 mg/dL. A inflamação ocular regrediu. Rafael se sente bem e pergunta se já pode suspender todos os medicamentos.','Durante a redução, após mais quatro semanas, reaparece dor ocular. A tosse está discreta e a saturação é normal. A melhora pulmonar não garante que todos os órgãos estejam controlados.'),
 bif('b2','Como responder ao retorno da dor ocular durante a redução?',[
 ('Reavaliar urgentemente com oftalmologia e ajustar o controle da doença conforme a atividade','controle','A visão exige avaliação específica; doença recidivante pode justificar estratégia poupadora de corticoide.'),
 ('Manter a retirada sem reavaliação porque cálcio e saturação normalizaram','visao','Marcadores de outros órgãos não excluem inflamação ocular ativa.')]),
 pg('controle','Reavaliação ocular','A uveíte voltou antes de provocar perda visual importante. A equipe ajusta o tratamento e discute terapia poupadora de corticoide diante da recidiva e dos riscos cumulativos.','O plano de seguimento passa a registrar separadamente visão, função pulmonar, cálcio e função renal.',segue='f1'),
 fim('f1','Controle em acompanhamento','A visão é preservada e o cálcio permanece normal. O paciente segue em redução supervisionada e monitorização de cada órgão.','O controle é longitudinal: remissão de um componente não equivale à remissão de toda a doença.','melhor'),
 pg('visao','Retorno não programado','Três semanas depois, Rafael retorna com visão turva e dor. A avaliação confirma inflamação persistente com complicação ocular, exigindo intensificação do tratamento.',segue='f2'),
 fim('f2','Complicação ocular','A evolução demanda tratamento mais intenso e deixa limitação visual residual neste cenário simulado.','O atraso em avaliar um sintoma novo permitiu dano em um órgão que não era acompanhado pelos exames de sangue.','pior'),
 pg('retrospectiva','Retrospectiva','A hipercalcemia abriu a investigação; o PTH suprimiu uma linha de hipóteses, mas não definiu a causa. A tomografia organizou a busca por tecido. O granuloma precisou de contexto e exclusão de alternativas.','A recorrência ocular mostrou por que o seguimento não pode depender apenas de cálcio, saturação ou melhora subjetiva.'),
 pg('referencias','Fontes e limites','Caso autoral; dados e desfechos simulados. A amostragem e a exclusão de alternativas se baseiam na diretriz ATS de diagnóstico e detecção de sarcoidose (2020): <a href="https://doi.org/10.1164/rccm.202002-0251ST" target="_blank" rel="noopener">Abrir referência</a>','Tratamento: ERS Clinical Practice Guidelines, 2021. <a href="https://doi.org/10.1183/13993003.04079-2020" target="_blank" rel="noopener">Abrir referência</a>',
 'O laudo tomográfico é textual e simulado. Não se atribuem achados a radiografias ou tomografias de doenças diferentes. A escolha de tratamento requer avaliação individual e da atividade de cada órgão.')
]
