const D = JSON.parse(document.getElementById('dados').textContent);
const prontos=D.casos.filter(c=>c.pronto), futuros=D.casos.filter(c=>!c.pronto);
const simbolo='<svg viewBox="0 0 24 24" aria-hidden="true"><rect x="3" y="3" width="7" height="7" rx="2"/><rect x="14" y="3" width="7" height="7" rx="2"/><rect x="3" y="14" width="7" height="7" rx="2"/><rect x="14" y="14" width="7" height="7" rx="2"/></svg>';
document.getElementById('topo').innerHTML='<nav class="barra"><span class="identidade">'+simbolo+'Casos clínicos</span><span class="edicao">Biblioteca de ensino</span></nav>'
 +'<div class="intro"><div><p class="sobretitulo">Investigação · Discussão · Decisão</p><h1>Biblioteca de casos</h1><p class="descricao">Escolha uma história. Conduza a investigação, acompanhe a evolução e discuta as decisões em cada etapa.</p></div><div class="acervo"><b>'+String(prontos.length).padStart(2,'0')+'</b><span>casos disponíveis<br>para conduzir em aula</span></div></div>'
 +'<div class="ferramentas"><h2>Apresentações</h2><label class="busca"><svg viewBox="0 0 24 24" aria-hidden="true"><circle cx="10" cy="10" r="6"/><path d="m15 15 5 5"/></svg><input id="busca" type="search" placeholder="Buscar no acervo" aria-label="Buscar casos por título" autocomplete="off"></label></div>';
const card=(c,n)=>'<a class="cs" href="'+c.arq+'" style="--cor:'+c.cor+'"><div class="capa" style="background-image:url('+c.capa+')"><span class="numero">CASO '+String(n+1).padStart(2,'0')+'</span></div><div class="corpo"><div class="esp">Clínica médica</div><h2>'+c.tt+'</h2><p class="sub">'+c.sub+'</p><div class="meta"><span>≈ '+c.min+' min</span><span>'+c.des+' desfechos</span></div><div class="abrir">Abrir apresentação <span aria-hidden="true">↗</span></div></div></a>';
function render(){const termo=document.getElementById('busca').value.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();const filtrados=prontos.map((c,n)=>({c,n})).filter(({c})=>(c.tt+' '+c.sub).normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().includes(termo));document.getElementById('grade').innerHTML=filtrados.length?filtrados.map(({c,n})=>card(c,n)).join(''):'<p class="vazio">Nenhum caso encontrado. Experimente outra palavra.</p>';}
document.getElementById('busca').addEventListener('input',render);render();
document.getElementById('rodape').innerHTML='<details class="proximos"><summary>Em desenvolvimento <span>'+futuros.length+' casos</span></summary><div>'+futuros.map(c=>'<p>'+c.tt+'</p>').join('')+'</div></details><div class="nota"><span class="selo">Sobre o acervo</span><p>'+D.rodape+'</p></div>';
