"""Paciente e trajetórias ficcionais. Não adapta um paciente publicado."""
from pathlib import Path
from motor.etapas import capa, pagina, p, vitais, topicos, lamina
from casos.novos import pg,q,labs,bif,fim
TITULO='O que ficou no pescoço'
RODAPE='Paciente ficcional · evoluções simuladas para ensino'
IMG=Path(__file__).parents[1]/'pulmao_rim'/'img'
BANCO=[]
ETAPAS=[
 capa(TITULO,fundo='',kicker='Caso interativo',procedencia='Paciente ficcional. Curso autoral e simulado.'),
 pg('historia','Apresentação','Marina, 27 anos, professora, procura atendimento por cansaço e febre ao final do dia há doze dias. Começou com dor de garganta e desconforto ao virar o pescoço. Continuou trabalhando na primeira semana, mas agora interrompe as aulas para se sentar.','Notou um caroço doloroso abaixo da orelha esquerda. A dor de garganta diminuiu; o caroço permaneceu. Tomou amoxicilina por sete dias, prescrita em uma consulta, sem desaparecimento da febre.'),
 pg('hda','História da doença atual','A temperatura medida em casa variou entre 37,8 e 38,6 °C. Nas últimas três noites precisou trocar a camiseta por suor. Perdeu 2 kg porque tem pouco apetite, sem dificuldade para engolir, diarreia ou vômitos. A dor cervical é contínua, pior à palpação, sem flutuação percebida.','Não tem tosse, dispneia, disúria ou dor dentária. Nega prurido generalizado, artrite, úlceras orais e lesões desencadeadas pelo sol. Não há relato de contato domiciliar com tuberculose. Uma colega de trabalho teve uma síndrome febril recente.'),
 pg('antecedentes','Antecedentes','Sem internações ou doenças crônicas conhecidas. Usa contraceptivo oral há quatro anos; durante a febre, paracetamol e a amoxicilina já concluída. Nega outros medicamentos, fitoterápicos ou drogas recreativas. Não fuma.','Mora em área urbana, sem viagens recentes. Convive com um gato adulto, sem arranhadura lembrada. Tem parceiro fixo e realizou teste de HIV há três anos. A mãe tem hipotireoidismo; não conhece história familiar de linfoma ou doença reumatológica.'),
 pagina('exame','Exame físico','',vitais(('PA','112/70 mmHg',False),('FC','98 bpm',False),('FR','16 irpm',False),('Temperatura','38,1 °C',True),('SpO₂','98% em ar ambiente',False)),topicos(('Estado geral','Alerta, hidratada, sem desconforto respiratório.'),('Cabeça e pescoço','Orofaringe sem exsudato. Linfonodos cervicais posteriores à esquerda, móveis e dolorosos, o maior de 2 cm. Sem rubor ou flutuação.'),('Cardiopulmonar','Ritmo regular, sem sopro. Ausculta pulmonar normal.'),('Abdome','Indolor, sem hepatoesplenomegalia palpável.'),('Pele, articulações e neurologia','Sem exantema, sinovite ou déficit focal. Sem linfonodos inguinais ou axilares palpáveis.')),so_kicker=True),
 q('p1',1,'Após doze dias de febre e adenopatia cervical dolorosa, qual abordagem inicial oferece mais informação útil?',[
 ('Hemograma com diferencial, marcadores inflamatórios e investigação infecciosa dirigida pela história',True,'Quantifica citopenias e orienta a seleção de testes; não pressupõe uma etiologia rara.'),
 ('PET-CT para separar adenopatia inflamatória de linfoma',False,'Captação metabólica ocorre nos dois processos; não substitui história, exames básicos ou tecido.'),
 ('Novo antibiótico de amplo espectro, utilizando a resposta como teste diagnóstico',False,'Sem foco bacteriano ou supuração, sucessivas tentativas podem adiar a investigação.'),
 ('Apenas ultrassom cervical, dispensando exames sistêmicos se os linfonodos forem dolorosos',False,'Dor não exclui doença sistêmica. Febre persistente e perda ponderal merecem avaliação conjunta.')]),
 labs('res1','Avaliação inicial',[
 ('Hemoglobina','11,7 g/dL','12–16 g/dL',True),('Leucócitos','2.900/mm³','4.000–11.000/mm³',True),('Neutrófilos','1.500/mm³','1.500–7.500/mm³',False),('Plaquetas','188.000/mm³','150.000–400.000/mm³',False),('Proteína C reativa','24 mg/L','<5 mg/L',True),('LDH','330 U/L','120–250 U/L',True),('Creatinina','0,8 mg/dL','0,6–1,1 mg/dL',False),('AST / ALT','42 / 47 U/L','até 35 / 35 U/L',True)],'A equipe colhe os exames para avaliar a repercussão sistêmica.'),
 pg('evolucao1','Terceira semana','A febre persiste. Um segundo linfonodo torna-se palpável à direita. Marina continua estável, mas falta ao trabalho. O esfregaço não mostra blastos; há alguns linfócitos reativos. A ultrassonografia mostra múltiplos linfonodos cervicais aumentados, sem coleção drenável.','Hemoculturas não apresentam crescimento. Teste combinado para HIV é negativo. O padrão sorológico para EBV é de infecção passada: VCA IgG e EBNA positivos, VCA IgM negativo. Testes para toxoplasmose e Bartonella não sustentam infecção recente.'),
 q('p2',2,'A leucopenia acompanha febre persistente e linfonodos sem supuração. Quais duas conclusões são justificadas?',[
 ('O padrão sorológico apresentado confirma mononucleose aguda',False,'IgG com EBNA e sem IgM favorece infecção passada; não explica automaticamente a doença atual.'),
 ('A avaliação deve manter causas infecciosas, inflamatórias e neoplásicas',True,'Nenhum dado isolado separa esses grupos. A evolução passa a importar mais que a dor do linfonodo.'),
 ('A elevação de LDH confirma linfoma',False,'LDH é inespecífica e pode aumentar por inflamação ou destruição celular.'),
 ('Persistência e progressão tornam razoável obter tecido com arquitetura preservada',True,'O crescimento durante a investigação e os sintomas sistêmicos justificam diagnóstico histológico.')]),
 pagina('rx','Investigação torácica','',p('A radiografia de tórax não mostra alteração relevante. A ausência de achados torácicos não encerra a investigação da adenopatia cervical.'),lamina_=lamina('rx_torax_normal.jpg','Radiografia de tórax','Imagem comparativa de outro paciente. Não é documentação de Marina.','Mikael Häggström · Wikimedia Commons · CC0'),so_kicker=True),
 bif('b1','A paciente permanece estável, mas o linfonodo maior atingiu 2,8 cm. Qual conduta você adota?',[
 ('Providenciar biópsia excisional de um linfonodo acessível','tecido','Preserva a arquitetura e permite investigar neoplasia e inflamação; reservar material para microbiologia conforme a suspeita.'),
 ('Prescrever prednisona antes de obter tecido, pela persistência dos sintomas','corticoide','Pode reduzir febre e tamanho dos linfonodos sem esclarecer a causa, dificultando a interpretação posterior.'),
 ('Manter observação com retorno em 48–72 horas e critérios explícitos de alarme','observacao','A estabilidade permite acompanhamento curto, mas crescimento ou piora exige abandonar a espera.')]),
 pg('corticoide','Após o tratamento','A febre cede por quatro dias e o linfonodo fica menos doloroso. Na redução do corticoide, os sintomas retornam. Marina interpreta a melhora como confirmação de doença autoimune, mas ainda não existe diagnóstico.','A equipe revê a hipótese e organiza a retirada supervisionada e a obtenção de tecido. A biópsia não deve ser substituída por novos ciclos empíricos.',segue='tecido'),
 pg('observacao','Reavaliação','Em três dias, a temperatura chega a 39 °C. Não há instabilidade hemodinâmica, mas a dor limita a alimentação. Leucócitos caem para 2.500/mm³ e o linfonodo permanece aumentado.','A evolução muda a relação entre benefício e risco da espera. A equipe solicita avaliação para biópsia excisional.',segue='tecido'),
 pg('tecido','Biópsia do linfonodo','Um linfonodo cervical é retirado. A histologia inicial descreve áreas de necrose com abundantes fragmentos nucleares e histiócitos, sem população linfoide monomórfica. Não há granulomas bem formados.','A citometria não identifica população clonal. Pesquisa de bacilos álcool-ácido resistentes e fungos é negativa; culturas seguem em processamento. A hematopatologia solicita correlação com manifestações sistêmicas.'),
 q('p3',3,'O laudo preliminar é de linfadenite necrosante, sem clone linfoide. Qual informação adicional melhor ajuda a interpretar o padrão?',[
 ('Presença de neutrófilos, características dos histiócitos e evidências clínicas e sorológicas de lúpus',True,'O padrão precisa ser distinguido de infecção supurativa e linfadenite associada a lúpus.'),
 ('Intensidade da captação no PET-CT',False,'Atividade metabólica não resolve o diagnóstico diferencial desse padrão histológico.'),
 ('Resposta imediata a novo antibiótico',False,'Não define o mecanismo da necrose nem substitui a revisão do tecido.'),
 ('Título isolado de anticorpo antinuclear, sem correlação clínica',False,'Um resultado isolado não estabelece doença sistêmica nem explica sozinho a histologia.')]),
 labs('res2','Investigação complementar',[
 ('FAN','Negativo','Negativo',False),('Anti-DNA nativo','Negativo','Negativo',False),('C3 / C4','112 / 25 mg/dL','90–180 / 10–40 mg/dL',False),('Urina','Sem hematúria ou proteinúria','Ausência',False),('Ferritina','480 ng/mL','15–150 ng/mL',True),('Triglicerídeos','126 mg/dL','<150 mg/dL',False),('Fibrinogênio','390 mg/dL','200–400 mg/dL',False)],'Sem artrite, lesões mucocutâneas ou alteração renal na reavaliação.'),
 pg('patologia','Revisão anatomopatológica','A revisão mostra necrose paracortical com cariorrexe, histiócitos de núcleos crescentiformes e células dendríticas plasmocitoides. Neutrófilos são escassos ou ausentes nas áreas necróticas. Não há corpos hematoxilínicos identificados.','O conjunto, correlacionado à apresentação e à exclusão das alternativas, sustenta linfadenite necrosante histiocítica, ou doença de Kikuchi–Fujimoto. A ausência de critérios atuais de lúpus não dispensa seguimento.'),
 q('p4',4,'Com diagnóstico estabelecido e sem disfunção orgânica, quais duas medidas são mais apropriadas?',[
 ('Quimioterapia por semelhança clínica com linfoma',False,'Sintomas constitucionais não autorizam tratar neoplasia quando o tecido demonstra outro processo.'),
 ('Controle de dor e febre, hidratação e reavaliação clínica programada',True,'O curso frequentemente é autolimitado; intensidade e duração dos sintomas orientam necessidade de escalada.'),
 ('Antituberculosos apesar da ausência de evidência microbiológica ou histológica',False,'O diagnóstico de linfadenite necrosante não equivale a tuberculose.'),
 ('Acompanhar recorrência e aparecimento de manifestações autoimunes',True,'Sintomas novos requerem reavaliação; a associação com lúpus torna relevante o seguimento.')]),
 pg('tratamento','Tratamento e acompanhamento','Marina recebe analgesia e orientação para manter hidratação. Não há indicação de antibiótico para a linfadenite demonstrada. A equipe agenda retorno e explica que a regressão dos linfonodos pode ser mais lenta que o desaparecimento da febre.','Corticoterapia fica reservada para doença importante ou refratária após revisão diagnóstica. A melhora sintomática, por si, não seria evidência suficiente para o diagnóstico.'),
 pg('retorno','Quatro semanas depois','Marina está afebril há oito dias. Os linfonodos diminuíram, mas ainda podem ser palpados. Hemoglobina é 12,1 g/dL, leucócitos 4.300/mm³ e PCR 4 mg/L. Ela voltou a trabalhar meio período.','Seis meses depois, relata artralgias nas mãos e uma erupção após exposição solar. Não há dispneia nem edema. São informações novas, não uma recaída automaticamente atribuível à mesma doença.'),
 bif('b2','Diante das novas manifestações, qual caminho você escolhe?',[
 ('Reexaminar e repetir avaliação dirigida para doença autoimune, incluindo urina e função renal','seguimento','Uma doença associada pode surgir posteriormente; é necessário verificar critérios e acometimento de órgãos.'),
 ('Atribuir tudo à doença já conhecida e encerrar a investigação','encerramento','O fechamento prematuro impede reconhecer uma mudança do quadro.')]),
 pg('seguimento','Nova avaliação','O exame confirma sinovite discreta. Há FAN positivo em título alto, anti-DNA nativo positivo, consumo de complemento e proteinúria de 0,8 g/g. A equipe encaminha para avaliação reumatológica e renal.','Neste ramo ficcional, a avaliação subsequente estabelece lúpus sistêmico. Isso não invalida automaticamente a primeira biópsia: a relação entre os quadros exige revisão longitudinal.',segue='f1'),
 fim('f1','Seguimento mantido','A paciente permanece em acompanhamento, com investigação do acometimento renal e tratamento dirigido à doença agora demonstrada.','Reconhecer manifestações novas evita transformar um diagnóstico anterior em explicação universal. Este desfecho é simulado, não uma previsão individual.','melhor'),
 pg('encerramento','Dois meses depois','Sem reavaliação, Marina retorna com edema e urina espumosa. A proteinúria é de 2,4 g/g e a creatinina subiu de 0,8 para 1,5 mg/dL. A investigação autoimune e renal é iniciada nesse momento.',segue='f2'),
 fim('f2','Investigação retomada','O diagnóstico da nova doença é feito mais tarde, já com lesão renal que exige investigação e tratamento.','Neste cenário simulado, o prejuízo decorre de ignorar manifestações novas; não significa que toda pessoa com Kikuchi desenvolverá lúpus.','pior'),
 pg('retrospectiva','Retrospectiva','Dor no linfonodo, leucopenia e LDH elevada não foram diagnósticos. O ponto de mudança foi a persistência com progressão, que justificou obter arquitetura ganglionar.','A biópsia respondeu à pergunta daquele momento. O seguimento precisou continuar aberto a novos problemas. Resposta a corticoide não substituiu tecido e não definiu etiologia.'),
 pg('referencias','Fontes e limites','Caso autoral e ficcional. Dados e percursos foram construídos para discussão; não reproduzem um paciente publicado.','Dumas et al. Kikuchi-Fujimoto Disease: Retrospective Study of 91 Cases. Medicine, 2014. <a href="https://pmc.ncbi.nlm.nih.gov/articles/PMC4602439/" target="_blank" rel="noopener">Abrir referência</a>','Radiografia comparativa: Mikael Häggström, Wikimedia Commons, CC0. As páginas de patologia apresentam laudo simulado, sem atribuir achados a uma figura não validada.')
]
